### ISSUE TITLE
intermittent kubedns responses for kubernetes service endpoints (1.3.5)

### ISSUE THREAD

**Issue by namliz** [cncf/demo#63]
kubernetes/kubernetes#28497

Tl;dr on this particular saga -- multiple people with various types of environments/clusters experience kubedns connectivity issues. 

What this means is that if you lookup a service internal to the cluster it sometimes doesn't resolve. This is core functionality and a show stopper. Reproducible but currently we don't understand why (I've suggested MountVolumes which is supposed to be a background loop is blocking somehow, even captured it on video).

**Comment by namliz** [comment]
Listing dupes here so I can close some browser tabs:  
kubernetes/kubernetes#16836, kubernetes/kubernetes#30139, kubernetes/kubernetes#18934, kubernetes/kubernetes/#22161, kubernetes/kubernetes#22823

**Comment by dankohn** [comment]
Love the video.

On Tue, Aug 30, 2016 8:56 AM, Eugene notifications@github.com wrote:
Listing dupes here so I can close some browser tabs:

kubernetes/kubernetes#16836 , kubernetes/kubernetes#30139 , kubernetes/kubernetes#18934 , kubernetes/kubernetes/#22161, kubernetes/kubernetes#22823

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub , or mute the thread .

-- Dan Kohn <mailto: dan@linuxfoundation.org > Executive Director, Cloud Native Computing Foundation < https://cncf.io/ >
tel:+1-415-233-1000
